from typing import Final

CATEGORY_TO_CLASSTYPE: dict[str, str] = {
    "Web Application Attack":                          "web-application-attack",
    "A Network Trojan was detected":                   "trojan-activity",
    "Malware Command and Control Activity Detected":   "command-and-control",
    "Domain Observed Used for C2 Detected":            "domain-c2",
    "Exploit Kit Activity Detected":                   "exploit-kit",
    "Executable code was detected":                    "shellcode-detect",
    "Targeted Malicious Activity was Detected":        "targeted-activity",
    "Attempted Administrator Privilege Gain":          "attempted-admin",
    "Successful Administrator Privilege Gain":         "successful-admin",
    "Attempted User Privilege Gain":                   "attempted-user",
    "Unsuccessful User Privilege Gain":                "unsuccessful-user",
    "Successful User Privilege Gain":                  "successful-user",
    "Successful Credential Theft Detected":            "credential-theft",
    "Potential Corporate Privacy Violation":           "policy-violation",
    "Inappropriate Content was Detected":              "inappropriate-content",
    "Misc Attack":                                     "misc-attack",
    "Potentially Bad Traffic":                         "bad-unknown",
    "Attempted Denial of Service":                     "attempted-dos",
    "Denial of Service":                               "successful-dos",
    "Detection of a Denial of Service Attack":         "denial-of-service",
    "Attempted Information Leak":                      "attempted-recon",
    "Information Leak":                                "successful-recon-limited",
    "Large Scale Information Leak":                    "successful-recon-largescale",
    "A suspicious string was detected":                "string-detect",
    "A suspicious filename was detected":              "suspicious-filename-detect",
    "An attempted login using a suspicious username was detected": "suspicious-login",
    "Attempt to login by a default username and password":         "default-login-attempt",
    "A client was using an unusual port":              "unusual-client-port-connection",
    "Detection of a non-standard protocol or event":   "non-standard-protocol",
    "Device Retrieving External IP Address Detected":  "external-ip-check",
    "access to a potentially vulnerable web application": "web-application-activity",
    "Possible Social Engineering Attempted":           "social-engineering",
    "Crypto Currency Mining Activity Detected":        "coin-mining",
    "Possibly Unwanted Program Detected":              "pup-activity",
    "Decode of an RPC Query":                          "rpc-portmap-decode",
    "A system call was detected":                      "system-call-detect",
    "Not Suspicious Traffic":                          "not-suspicious",
    "Unknown Traffic":                                 "unknown",
    "Misc activity":                                   "misc-activity",
    "Generic ICMP event":                              "icmp-event",
    "Generic Protocol Command Decode":                 "protocol-command-decode",
    "Detection of a Network Scan":                     "network-scan",
    "A TCP connection was detected":                   "tcp-connection",
}

CLASSTYPE_SCORE_RANGE: dict[str, tuple[int, int]] = {
    "web-application-attack":         (70, 95),
    "trojan-activity":                (75, 95),
    "command-and-control":            (80, 100),
    "domain-c2":                      (80, 100),
    "exploit-kit":                    (75, 95),
    "shellcode-detect":               (75, 95),
    "targeted-activity":              (70, 95),
    "attempted-admin":                (65, 90),
    "successful-admin":               (85, 100),
    "attempted-user":                 (60, 85),
    "unsuccessful-user":              (55, 80),
    "successful-user":                (70, 90),
    "credential-theft":               (80, 100),
    "policy-violation":               (60, 85),
    "inappropriate-content":          (50, 75),
    "misc-attack":                    (45, 70),
    "bad-unknown":                    (40, 65),
    "attempted-dos":                  (55, 80),
    "successful-dos":                 (65, 85),
    "denial-of-service":              (60, 85),
    "attempted-recon":                (40, 65),
    "successful-recon-limited":       (45, 65),
    "successful-recon-largescale":    (55, 75),
    "string-detect":                  (35, 60),
    "suspicious-filename-detect":     (45, 70),
    "suspicious-login":               (45, 70),
    "default-login-attempt":          (45, 70),
    "unusual-client-port-connection": (35, 60),
    "non-standard-protocol":          (35, 60),
    "external-ip-check":              (30, 55),
    "web-application-activity":       (30, 55),
    "social-engineering":             (50, 75),
    "coin-mining":                    (50, 70),
    "pup-activity":                   (25, 50),
    "rpc-portmap-decode":             (25, 50),
    "system-call-detect":             (40, 65),
    "not-suspicious":                 (5,  25),
    "unknown":                        (20, 45),
    "misc-activity":                  (10, 35),
    "icmp-event":                     (10, 30),
    "protocol-command-decode":        (10, 30),
    "network-scan":                   (35, 60),
    "tcp-connection":                 (5,  20),
}

CLASSTYPE_RANK: dict[str, int] = {
    "web-application-attack": 3, "trojan-activity": 3,
    "command-and-control": 3,    "misc-attack": 3,
    "exploit-kit": 3,            "shellcode-detect": 3,
    "targeted-activity": 3,      "attempted-admin": 3,
    "successful-admin": 3,       "credential-theft": 3,
    "domain-c2": 3,              "successful-user": 3,
    "attempted-user": 3,         "policy-violation": 3,
    "bad-unknown": 2,            "network-scan": 2,
    "attempted-dos": 2,          "denial-of-service": 2,
    "coin-mining": 2,            "social-engineering": 2,
    "not-suspicious": 1,         "unknown": 1,
    "tcp-connection": 1,         "misc-activity": 1,
}
